version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpasswordhere
  my-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: yourpasswordhere
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8084:80"
    links:
      - my-wpdb:db